_target_: bioemu.shortcuts.FinetuneConfig

# Data parameters
data_batch_size: 1
shuffle: true
num_workers: 0

# Loss parameters
lambda_: 0.1
tol: 1.0e-07

# Training parameters
batch_size: 256
micro_batch_size: 4
num_epochs: 20
save_every_n_epochs: 2
val_every_n_epochs: 2
lr: 5.0e-04
betas: [0.9, 0.999]
weight_decay: 1.0e-04
eta_min: 1.0e-05
